[tool.poetry]
name = "shakah"
version = "2.0.1"
description = ""
authors = ["kivo360 <kivo360@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sqlmodel = "^0.0.6"
loguru = "^0.5.3"

pydantic = {extras = ["dotenv", "email"], version = "^1.9.0"}
dynaconf = {extras = ["vault", "redis"], version = "^3.1.7"}
decorator = "^5.1.1"
devtools = "^0.8.0"
fastcore = "^1.3.27"
psycopg2 = "^2.9.3"
import-linter = "^1.2.6"
cytoolz = "^0.11.2"


[tool.poetry.dev-dependencies]
ipykernel = "^6.6.1"
mypy = "^0.931"
autopep8 = "^1.6.0"
pytest-testmon = "^1.2.2"
pytest-watch = "^4.2.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


# [tool.isort]

